language: php

php:
  - 5.4

env:
  - DB=mysql

matrix:
  include:
    - php: 5.4
      env:
        - PHPCS=1

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - sh -c "mysql -e 'CREATE DATABASE mytwittertravis;'"
  - sh -c "mysql -u travis mytwittertravis < schema.sql"
  - echo "<?php return array('test' => array('driver' => 'mysql', 'user' => 'travis', 'pass'=>'', 'dbname' => 'mytwittertravis', 'host'=>'localhost'));" > App/database.php

script:
  - phpunit
