<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MyTwitter<?= isset($title_for_layout) ? ' - ' . $title_for_layout : '' ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- bootstrap css -->
	<link rel="stylesheet" href="css/bootstrap.min.css" media="screen">
	<link rel="stylesheet" href="css/app.css" media="screen">
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="/">MyTwitter</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li class="active"><a href="/">Home</a></li>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
<!-- body closes on footer.phtml -->