<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>MyTwitter<?= isset($title_for_layout) ? ' - ' . $title_for_layout : '' ?></title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- bootstrap css -->
	<link rel="stylesheet" href="/css/bootstrap.min.css" media="screen">
	<link rel="stylesheet" href="/css/app.css" media="screen">
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="#">MyTwitter</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<?php if($Session->isAuthenticated()): ?>
							<li class="active"><a href="/users">Home</a></li>
							<li><a href="/users/find">Buscar amigos</a></li>
							<li><a href="/users/logout">Sair</a></li>
						<?php else: ?>
							<li class="active"><a href="/">Home</a></li>
						<?php endif; ?>
					</ul>
				</div>
			</div>
		</div>
	</div>
	<div class="container">
	<?php
		$message = $Session->read('message');
		$messageCls = $Session->read('message-class');
		$Session->write("message", "");
		if($message):
	?>
	<div class="row">
		<div class="alert <?=!empty($messageCls) ? 'alert-'. $messageCls : ''?>">
			<button type="button" class="close" data-dismiss="alert">&times;</button>
			<strong>Atenção!</strong> <?=$message?>
		</div>
	</div>
	<?php endif; ?>
<!-- body closes on footer.phtml -->