<div class="row">
	<div class="span6 offset3">

		<div class="row">
			<form class="form-search" action="/Messages/find" method="POST">
				<fieldset>
					<legend>Busca por hashtag (#)</legend>
					<div class="input-prepend">
						<span class="add-on">#</span>
						<input name="find[term]" type="text" class="input span5 search-query" placeholder="Não utilize o # (hashtag)">
					</div>
					<button type="submit" class="btn">Buscar</button>
				</fieldset>
			</form>
		</div>

		<div class="row">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Últimas publicações</th>
					</tr>
				</thead>
				<tbody>
			<?php if(isset($messages) && !empty($messages)): ?>
				<?php foreach($messages as $message): ?>
				<?php
					$text = $Hashtag->replaceHashtags($message['text']);
				?>
					<tr>
						<td>
							<strong>@<?=$message['login']?>, <?=(new DateTime($message['created_at']))->format('d/m H:i')?>h,  disse: </strong><br/>
							&nbsp;<?=$text?>
						</td>
					</tr>
				<?php endforeach; ?>
			<?php else: ?>
					<tr>
						<td>
							Nenhuma mensagem foi encontrada
						</td>
					</tr>
			<?php endif; ?>
				</tbody>
			</table>
			<?php
				$page = isset($_GET['pg']) ? $_GET['pg'] : 1;
			?>
			<ul class="pager">
				<?php if($page != 1): ?>
					<li class="previous">
						<a href="/messages/find/hash:<?=$term?>?pg=<?=($page-1)?>">&larr; Anterior</a>
					</li>
				<?php else: ?>
					<li class="previous disabled">
						<a href="#">&larr; Anterior</a>
					</li>
				<?php endif; ?>
				<li class="next">
					<a href="/messages/find/hash:<?=$term?>?pg=<?=++$page?>">Próximo &rarr;</a>
				</li>
			</ul>
		</div>
	</div>
</div>