<div class="row">
	<div class="span6 offset3">

		<div class="row">
			<form class="form-search" action="/Messages/find" method="POST">
				<fieldset>
					<legend>Busca por hashtag (#)</legend>
					<div class="input-prepend">
						<span class="add-on">#</span>
						<input name="find[term]" type="text" class="input span5 search-query" placeholder="Não utilize o # (hashtag)">
					</div>
					<button type="submit" class="btn">Buscar</button>
				</fieldset>
			</form>
		</div>

		<div class="row">
			<table class="table table-striped table-bordered">
				<thead>
					<tr>
						<th>Últimas publicações</th>
					</tr>
				</thead>
				<tbody>
			<?php if(isset($messages) && !empty($messages)): ?>
				<?php foreach($messages as $message): ?>
				<?php
					$text = $Hashtag->replaceHashtags($message['text']);
				?>
					<tr>
						<td>
							<strong>@<?=$message['login']?>, <?=(new DateTime($message['created_at']))->format('d/m H:i')?>h,  disse: </strong><br/>
							&nbsp;<?=$text?>
						</td>
					</tr>
				<?php endforeach; ?>
			<?php else: ?>
					<tr>
						<td>
							Nenhuma mensagem foi encontrada
						</td>
					</tr>
			<?php endif; ?>
				</tbody>
			</table>
		</div>
	</div>
</div>