<div class="row">
	<div class="span6 offset3">
		<form class="form-search" action="/Users/find" method="POST">
			<fieldset>
				<legend>Encontre seus amigos</legend>
				<input name="find[term]" type="text" class="input span5 search-query" placeholder="Digite o nome ou login para buscar">
				<button type="submit" class="btn">Buscar</button>
			</fieldset>
		</form>
		<?php if(isset($usuarios) && !empty($usuarios)): ?>
			<table class="table table table-striped table-bordered">
				<thead>
					<tr>
						<th colspan="3">Resultado da busca</th>
					</tr>
					<tr>
						<th>Nome</th>
						<th>Login</th>
						<th>&nbsp;</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach($usuarios as $user): ?>
						<tr>
							<td><?=$user['nome']?></td>
						 	<td><?=$user['login']?></td>
						 	<td>
								<form class="form-inline" action="/Users/follow" method="POST">
									<input type="hidden" name="follow[user_id]" value="<?=$user['id']?>">
									<input type="submit" value="Seguir" class="btn btn-success" />
								</form>
							</td>
						</tr>
					</p>
				<?php endforeach; ?>
				</tbody>
			</table>
		<?php elseif(isset($usuarios) && empty($usuarios)): ?>
			<ul id="users-find-list">
				<li>Nenhum usuário encontrado</li>
			</ul>
		<?php endif; ?>
	</div>
</div>