<div class="row">
	<div class="span4">
		<div class="row">
			<form class="span3" action="/Messages" method="POST">
				<h3>Nova Mensagem</h3>
				<div class="controls">
					<textarea id="message" name="message[text]" class="span3" placeholder="O que você está pensando?" rows="5"></textarea>
				</div>

				<div class="controls">
					<button type="submit" class="btn btn-primary">Publicar</button>
				</div>
			</form>
		</div>
	</div>
	<div class="span8">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Últimas publicações</th>
				</tr>
			</thead>
			<tbody>
		<?php if(isset($messages) && !empty($messages)): ?>
			<?php foreach($messages as $message): ?>
				<tr>
					<td>
						<strong>@<?=$message['login']?>, <?=(new DateTime($message['created_at']))->format('d/m H:i')?>h,  disse: </strong><br/>
						&nbsp;<?=$message['text']?>
					</td>
				</tr>
			<?php endforeach; ?>
		<?php else: ?>
				<tr>
					<td>
						Não há mensagens no momento
					</td>
				</tr>
		<?php endif; ?>
			</tbody>
		</table>
	</div>
</div>