<div class="row">
	<div class="span4">
		<div class="row">
			<form class="span3" action="/Messages" method="POST">
				<h3>Nova Mensagem</h3>
				<div class="controls">
					<textarea id="message" name="message[text]" class="span3" placeholder="O que você está pensando?" rows="5"></textarea>
				</div>

				<div class="controls">
					<button type="submit" class="btn btn-primary">Publicar</button>
				</div>
			</form>
		</div>
	</div>
	<div class="span8">
		<h1>Essa é a página de dentro da aplicação</h1>
		<p>Bem-vindo ao MyTwitter, aqui você fica por dentro do que rola no mundo!</p>
	</div>
</div>