<div class="row">
	<div class="span4">
		<div class="row">
			<form class="span3" action="/Messages" method="POST">
				<h3>Nova Mensagem</h3>
				<div class="controls">
					<textarea id="message" name="message[text]" class="span3" placeholder="O que você está pensando?" rows="5"></textarea>
				</div>

				<div class="controls">
					<button type="submit" class="btn btn-primary">Publicar</button>
				</div>
			</form>
		</div>
	</div>
	<div class="span8">
		<table class="table table-striped table-bordered">
			<thead>
				<tr>
					<th>Últimas publicações</th>
				</tr>
			</thead>
			<tbody>
		<?php if(isset($messages) && !empty($messages)): ?>
			<?php foreach($messages as $message): ?>
				<?php $text = $Hashtag->replaceHashtags( $message['text'] ); ?>
				<tr>
					<td>
						<strong>@<?=$message['login']?>, <?=(new DateTime($message['created_at']))->format('d/m H:i')?>h,  disse: </strong><br/>
						&nbsp;<?=$text?>
					</td>
				</tr>
			<?php endforeach; ?>
		<?php else: ?>
				<tr>
					<td>
						Não há mensagens no momento
					</td>
				</tr>
		<?php endif; ?>
			</tbody>
		</table>
		<?php
			$page = isset($_GET['pg']) ? $_GET['pg'] : 1;
		?>
		<ul class="pager">
			<?php if($page != 1): ?>
				<li class="previous">
					<a href="/users?pg=<?=($page-1)?>">&larr; Anterior</a>
				</li>
			<?php else: ?>
				<li class="previous disabled">
					<a href="#">&larr; Anterior</a>
				</li>
			<?php endif; ?>
			<li class="next">
				<a href="/users?pg=<?=++$page?>">Próximo &rarr;</a>
			</li>
		</ul>
	</div>
</div>